object Version {
    const val kotlin = "1.3.61"
    const val kotlinCoroutines = "1.3.2"
    const val androidxAppcompat = "1.1.0"
    const val androidxConstraintlayout = "1.1.3"
    const val androidxLifecycle = "2.2.0-rc03"
    const val androidxRoom = "2.2.2"
    const val androidxTestRunner = "1.2.0"
    const val androidxTestJunit = "1.1.1"
    const val androidxTestEspresso = "3.2.0"
    const val lichComponent = "2.1.0"
    const val lichViewmodel = "2.0.0-rc1"
    const val autoService = "1.0-rc6"
    const val dagger = "2.25.2"
    const val mockk = "1.9.3"
    const val robolectric = "4.3"
}
